"""Generate code to tabulate reports for each user

Revision ID: 8c006f31df47
Revises: b09067f08704
Create Date: 2025-05-30 09:11:26.149942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c006f31df47'
down_revision: Union[str, None] = 'b09067f08704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'habits_new',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String, nullable=False),  # NOT NULL enforced
        sa.Column('description', sa.String),
        sa.Column('time_period', sa.String),
        sa.Column('category', sa.String),
        sa.Column('frequency', sa.Integer),
    )

    # 2. Copy data from old table (only rows with non-null names)
    op.execute("""
        INSERT INTO habits_new (id, name, description, time_period, category, frequency)
        SELECT id, name, description, time_period, category, frequency
        FROM habits
        WHERE name IS NOT NULL
    """)

    # 3. Drop old table
    op.drop_table('habits')

    # 4. Rename new table to original name
    op.rename_table('habits_new', 'habits')
